version: '3.9'

services:
  web:
    build: .
    container_name: order_microservice
    ports:
      - "5003:5003"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: prod
      # DATABASE_URL: postgresql://postgres:SHMIgtBBk1zQKYhMSmDX@database-1.c3u0oys8ik2c.eu-west-2.rds.amazonaws.com:5432/grocery_orders
      # CONFIG_FILE_PATH : /config/appsettings.prod.config
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"