version: '3.9'

services:
  db:
    image: postgres:17
    container_name: orders_Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: grocery_orders
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: order_microservice
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: prod
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
